### ISSUE TITLE
[Feature] Todo 전체 조회 템플릿 만들기

### ISSUE THREAD

**Issue by onlynyang** [onlynyang/Todo-List-Practice#1]
## Issue Type
- [x] Feature : 기능 구현
- [ ] Fix : 버그 수정
- [ ] Comment : 주석 추가
- [ ] Docs : 문서 수정
- [ ] Rename : 이름 변경
- [ ] Remove : 삭제

## Purpose
> Todo list 전체 조회 페이지 생성 연습

## To do
> 모델 - 템플릿 - 뷰 - url
