### ISSUE TITLE
[Feature] Todo 상세 조회 기능 구현

### ISSUE THREAD

**Issue by onlynyang** [onlynyang/Todo-List-Practice#3]
## Issue Type
- [x] Feature : 기능 구현
- [ ] Fix : 버그 수정
- [ ] Comment : 주석 추가
- [ ] Docs : 문서 수정
- [ ] Rename : 이름 변경
- [ ] Remove : 삭제

## Purpose
> detail 구현 연습

## To do
> 템플릿 - 뷰 - url
