### ISSUE TITLE
[Feature] Todo 생성 기능 구현

### ISSUE THREAD

**Issue by onlynyang** [onlynyang/Todo-List-Practice#5]
## Issue Type
- [x] Feature : 기능 구현
- [ ] Fix : 버그 수정
- [x] Comment : 주석 추가
- [ ] Docs : 문서 수정
- [ ] Rename : 이름 변경
- [ ] Remove : 삭제

## Purpose
> create 연습

## To do
> 템플릿 - 뷰 - url

## Note
> 모든 파일 라인 하나하나 읽어보면서 주석 추가(html도..)
